### ISSUE TITLE
Source: helpers/frame.py:77 by Hacs_dwd Pollenflug

### ISSUE THREAD

**Issue by Johnyboy1984** [mampfes/hacs_dwd_pollenflug#13]
Good day,

Today I looked at my Home Assistant log and found this entry in the log:

![image](https://user-images.githubusercontent.com/96473114/217899839-0ace829c-af60-4b61-8159-dfd606ccb891.png)

HA - Version: 2023.2.3
HA Operationen System:  9.5

Since Home Assistant pointed this out to me, I thought I'd share it with you so you might be able to provide an update. Thank you in advance for your efforts.

Best regards

Johnnyboy1984

**Comment by mampfes** [comment]
This should be fixed in version 1.0.2. Did you already update?

**Comment by Johnyboy1984** [comment]
I am currently using the version. 1.0.1 because version 1.0.2 requires HA version 2023.3.0.

![image](https://user-images.githubusercontent.com/96473114/217921374-89525b19-3a90-4a70-9290-6242d752c7ad.png)

**Comment by mampfes** [comment]
Oh, damn, this is a typo. It should have been 2023.2. I added a new release 1.0.3 which should work with HA 2023.2

**Comment by mampfes** [comment]
fixed with Release 1.0.3
