### ISSUE TITLE
Installation not possible on Home Assistant 2023.5.2

### ISSUE THREAD

**Issue by mjmeierhoefer** [mampfes/hacs_dwd_pollenflug#15]
Clicking the link https://my.home-assistant.io/redirect/config_flow_start?domain=dwd_pollenflug to add the integration shows the following error:

"This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 9.5
Frontend 20230503.3 - latest

Hope you can fix it.
Thanx!

**Comment by mampfes** [comment]
This is strange because `DWD Pollenflug` provides a UI configuration interface. I also do not see this issue on my HA 2023.5.2 instance.

I assume an installation issue. How did you install it? Via HACS? Could you try to reinstall it?

**Comment by mjmeierhoefer** [comment]
Installation didn't work with the link provided above - direct install via HACS worked. Thanx.
