### ISSUE TITLE
integrations and platforms could not be set up

### ISSUE THREAD

**Issue by kriss2013** [mampfes/hacs_dwd_pollenflug#4]
the notification gives:

Invalid config
The following integrations and platforms could not be set up:

dwd_pollenflug.sensor
Please check your config and logs.

the log sas:
Logger: homeassistant.setup
Source: setup.py:317
First occurred: 8:44:38 AM (1 occurrences)
Last logged: 8:44:38 AM

Unable to prepare setup for platform dwd_pollenflug.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

I am running HA core-2021.9.7  and only update according to "don't fix it if it's not broken";-)

**Comment by mampfes** [comment]
Hi, you already gave yourself the answer: Your HA version is too old.

You can try version 1.0.0 of the integration, I think this one should be compatible. But you definitely can't participate in future enhancements than.

**Comment by kriss2013** [comment]
thanx a lot, oder lieber Danke schön ;-)
