### ISSUE TITLE
No attribut for state_in_2_days / state_in_2_days_desc

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_dwd_pollenflug#6]
First, thank you for your works!

I install the integration via HACS.

I get no attributes for state_in_2_days / state_in_2_days_desc

<img width="435" alt="image" src="https://user-images.githubusercontent.com/97361636/164945737-b2f85d39-897a-4d80-8453-3885359370c7.png">

**Comment by mampfes** [comment]
Data for "in 2 days" will be only provided on Friday by the DWD (to have a prediction for Sunday), Therefore the sensors sometimes show no data.
