### ISSUE TITLE
No config for region_id 40 (NRW)

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_dwd_pollenflug#7]
Dear @mampfes,

i live in NRW, which have the region_id = 40.
But i don't live in the sub-regions with partregion_id 41, 42 or 43

During the customizing, i muss select a sub-region.
Their is no "empty" value.

**Comment by mampfes** [comment]
The whole area of Germany is covered by the sub-regions. Please check [Gebietseinteilung](https://www.dwd.de/DE/leistungen/gefahrenindizespollen/Gebiete.html;jsessionid=6EFEC19F16B0D0204A19D135D464295E.live11041?nn=16102&lsbId=463856) and select your closest sub-region.

BTW: DWD does not provide data per region, only per sub-region. Therefore you can't select a region.
