### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Mangomc** [mampfes/hacs_dwd_pollenflug#9]
Hello. Dwd Stopped working for me

`2022-05-08 23:12:09 ERROR (SyncWorker_1) [custom_components.dwd_pollenflug] fetch data from DWD failed : HTTPSConnectionPool(host='opendata.dwd.de', port=443): Max retries exceeded with url: /climate_environment/health/alerts/s31fg.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))`

**Comment by GerdRuetten** [comment]
> Hello. Dwd Stopped working for me
> 
> `2022-05-08 23:12:09 ERROR (SyncWorker_1) [custom_components.dwd_pollenflug] fetch data from DWD failed : HTTPSConnectionPool(host='opendata.dwd.de', port=443): Max retries exceeded with url: /climate_environment/health/alerts/s31fg.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))`

I have the same issue.

The problem is, that the SSL-Certificat from DWD is expired, so the https-URL are invalid

```
NET::ERR_CERT_DATE_INVALID
Subject: opendata.dwd.de
Issuer: DFN-Verein Global Issuing CA
Expires on: 08.05.2022
Current date: 09.05.2022

```

Don't switch to an unsafe http-URL because the DWD-Side use HSTS!

Wait for DWD to fix the error

**Comment by GerdRuetten** [comment]
DWD has fix the problem.
The side is reach over a new SSL-Cert.
